apiVersion: v1
kind: PersistentVolume
metadata:
  name: twentycrm-db-pv
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
