apiVersion: v1
kind: PersistentVolume
metadata:
  name: twentycrm-server-pv
  namespace: twentycrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
